### ISSUE TITLE
Error when run fine-tune with bart_base model

### ISSUE THREAD

**Issue by phanxuanphucnd** [facebookresearch/bart_ls#5]
Hi,

When I use fine-tuning script from **bart_base** instead of **bart_large** and I have load checkpoint from [link](https://github.com/facebookresearch/fairseq/blob/main/examples/bart/README.md) instead of **model_100k.pt** like in the tutorial I get this problem:
```

RuntimeError: Error(s) in loading state_dict for BARTModel:
	Missing key(s) in state_dict: "encoder.layers.8.pool_attn.k_proj.weight", "encoder.layers.8.pool_attn.k_proj.bias", "encoder.layers.8.pool_attn.v_proj.weight", "encoder.layers.8.pool_attn.v_proj.bias", "encoder.layers.8.pool_attn.q_proj.weight", "encoder.layers.8.pool_attn.q_proj.bias", "encoder.layers.8.pool_attn.out_proj.weight", "encoder.layers.8.pool_attn.out_proj.bias", "encoder.layers.9.pool_attn.k_proj.weight", "encoder.layers.9.pool_attn.k_proj.bias", "encoder.layers.9.pool_attn.v_proj.weight", "encoder.layers.9.pool_attn.v_proj.bias", "encoder.layers.9.pool_attn.q_proj.weight", "encoder.layers.9.pool_attn.q_proj.bias", "encoder.layers.9.pool_attn.out_proj.weight", "encoder.layers.9.pool_attn.out_proj.bias", "encoder.layers.10.pool_attn.k_proj.weight", "encoder.layers.10.pool_attn.k_proj.bias", "encoder.layers.10.pool_attn.v_proj.weight", "encoder.layers.10.pool_attn.v_proj.bias", "encoder.layers.10.pool_attn.q_proj.weight", "encoder.layers.10.pool_attn.q_proj.bias", "encoder.layers.10.pool_attn.out_proj.weight", "encoder.layers.10.pool_attn.out_proj.bias", "encoder.layers.11.pool_attn.k_proj.weight", "encoder.layers.11.pool_attn.k_proj.bias", "encoder.layers.11.pool_attn.v_proj.weight", "encoder.layers.11.pool_attn.v_proj.bias", "encoder.layers.11.pool_attn.q_proj.weight", "encoder.layers.11.pool_attn.q_proj.bias", "encoder.layers.11.pool_attn.out_proj.weight", "encoder.layers.11.pool_attn.out_proj.bias". 
	size mismatch for encoder.embed_positions.weight: copying a param with shape torch.Size([1026, 1024]) from checkpoint, the shape in current model is torch.Size([16386, 1024]).

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train.py", line 13, in <module>
    cli_main()
  File "/home/phucpx/phucpx/bart_ls/fairseq-py/fairseq_cli/train.py", line 507, in cli_main
    distributed_utils.call_main(cfg, main)
  File "/home/phucpx/phucpx/bart_ls/fairseq-py/fairseq/distributed/utils.py", line 404, in call_main
    main(cfg, **kwargs)
  File "/home/phucpx/phucpx/bart_ls/fairseq-py/fairseq_cli/train.py", line 155, in main
    extra_state, epoch_itr = checkpoint_utils.load_checkpoint(
  File "/home/phucpx/phucpx/bart_ls/fairseq-py/fairseq/checkpoint_utils.py", line 255, in load_checkpoint
    extra_state = trainer.load_checkpoint(
  File "/home/phucpx/phucpx/bart_ls/fairseq-py/fairseq/trainer.py", line 514, in load_checkpoint
    raise Exception(
Exception: Cannot load model parameters from checkpoint ../checkpoints/model-large.pt; please ensure that the architectures match.
```

There seems to be a deviation in the encode position dimension.

How to fix them?

Thank

**Comment by phanxuanphucnd** [comment]
Hi, How to train from scratch?

**Comment by phanxuanphucnd** [comment]
I was able to handle it.
Thank
